### ISSUE TITLE
Incorrect message being sent when attempting to enable NightVision upon login

### ISSUE THREAD

**Issue by baailey** [OmegaWeaponDev/OmegaVision#11]
### issue-description

Set Night_Vision_Login to true in the config and don't give yourself omegavision.nightvision.login. Enable NightVision, log out and then back in, and try enabling NightVision again. The message that will display is that you're disabling NightVision, even though it is already disabled.

### Expected Behaviour

When trying to enable NightVision, it should say NightVision has been enabled.

### Debug Information

https://pastebin.com/CdfeYRs7

**Comment by OmegaWeaponDev** [comment]
Hi, 
Thanks for letting me know, I'll look into this in the next day or two when I have some free time. 

OmegaWeaponDev

**Comment by OmegaWeaponDev** [comment]
Hi @baailey,

The new update for OmegaVision (v2.5.1) should contain a fix for this issue. Please let me know if it is still re-occurring.

The behavior for Night Vision Login should only add night vision to the player if they:

1. Logout with it currently enabled
2. The setting in the config.yml has been enabled
3. They have the permission `omegavision.nightvision.login`

All three of those things need to be true in order for it to re-apply night vision when they log in. Otherwise, even if one of those things is false, it will mark them as not having night vision and remove it from them. Ready for them to re-apply it themselves.

Thanks,
OmegaWeaponDev

**Comment by baailey** [comment]
Fixed.
